### PR TITLE
allow custom middleware in config

### PR DESCRIPTION
**Pull request by rizkyarlin**
My default auth guard is `api`. I need to be able to assign a `auth:web` middleware so I can use this package. So this PR will give the user flexibility for middlewares.

A little backstory... I also ran into this problem in https://github.com/laravel/horizon (which really similar with this package), the solution was just like what I mentioned above. Luckily Horizon has `middleware` in its config file.

Anw, This is a really nice package!

### CODE REVIEW

**Comment by trianity** [comment]
@haruncpi Thank you for this excellent package.
@rizkyarlin I forked this package and your suggestion with a translations possibility is available here 
[https://packagist.org/packages/successdev/laravel-log-reader](https://packagist.org/packages/successdev/laravel-log-reader)

**Comment by rizkyarlin** [comment]
> @haruncpi Thank you for this excellent package.
> @rizkyarlin I forked this package and your suggestion with a translations possibility is available here
> https://packagist.org/packages/successdev/laravel-log-reader

Why didn’t you PR my fork to your fork?

**Comment by trianity** [comment]
@rizkyarlin I am sorry. I need the translations in my projects and I had to modify the package to create new packagist package, and in this case (changing name space) there will be conflict between packages.

**Comment by rizkyarlin** [comment]
that's okay! I was just asking 😄

**Comment by Luukdewaaier** [comment]
Will this be accepted?

**Comment by haruncpi** [comment]
Check v1.0.6
- Custom middleware support
- Minor UI changes

**Pull request closed without merging**
